#!/usr/bin/env node
import * as fs from 'fs';
import * as path from 'path';
import { run_cmd, Style } from './pickle-utils.js';
export function createPR(sessionDir) {
    const statePath = path.join(sessionDir, 'state.json');
    if (!fs.existsSync(statePath)) {
        throw new Error('state.json not found');
    }
    const state = JSON.parse(fs.readFileSync(statePath, 'utf-8'));
    const repoPath = state.working_dir;
    if (!repoPath) {
        throw new Error('working_dir not set in state.json');
    }
    if (!fs.existsSync(repoPath)) {
        throw new Error(`working_dir does not exist: ${repoPath}`);
    }
    // Verify it's a git repo
    try {
        run_cmd(['git', 'rev-parse', '--git-dir'], { cwd: repoPath });
    } catch {
        throw new Error(`Not a git repository: ${repoPath}`);
    }
    // Verify at least one remote exists
    const remotes = run_cmd(['git', 'remote'], { cwd: repoPath, check: false });
    if (!remotes.trim()) {
        throw new Error('No git remotes configured — cannot create PR');
    }
    const branch = run_cmd(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], { cwd: repoPath }).trim();
    const prompt = state.original_prompt || 'unknown task';
    const title = `Pickle Rick: ${prompt.length > 50 ? prompt.slice(0, 50) + '...' : prompt}`;
    const body = `Generated by Pickle Rick.\n\nSession: ${path.basename(sessionDir)}\nPrompt: ${prompt}`;
    try {
        const output = run_cmd(['gh', 'pr', 'create', '--title', title, '--body', body], {
            cwd: repoPath,
        });
        return output.trim();
    }
    catch (err) {
        throw new Error(`Failed to create PR: ${err.message}`);
    }
}
// CLI
if (process.argv[1] && path.basename(process.argv[1]) === 'pr-factory.js') {
    const sessionDir = process.argv[2];
    if (!sessionDir) {
        console.error('Usage: node pr_factory.js <session_dir>');
        process.exit(1);
    }
    try {
        const url = createPR(sessionDir);
        console.log(`${Style.GREEN}PR Created: ${url}${Style.RESET}`);
    }
    catch (err) {
        console.error(`${Style.RED}Error: ${err.message}${Style.RESET}`);
        process.exit(1);
    }
}
