#!/usr/bin/env node
import * as fs from 'fs';
import * as path from 'path';
import { run_cmd, Style } from './pickle-utils.js';
import { State } from '../types/index.js';

export function createPR(sessionDir: string): string {
  const statePath = path.join(sessionDir, 'state.json');
  if (!fs.existsSync(statePath)) {
    throw new Error('state.json not found');
  }

  let state: State;
  try {
    state = JSON.parse(fs.readFileSync(statePath, 'utf-8')) as State;
  } catch {
    throw new Error('state.json is corrupt or unreadable');
  }
  const repoPath = state.working_dir;
  if (!repoPath) {
    throw new Error('state.json is missing working_dir — cannot determine target repository');
  }

  const prompt = state.original_prompt || '';
  const title = prompt.length > 50
    ? `Pickle Rick: ${prompt.slice(0, 50)}...`
    : `Pickle Rick: ${prompt}`;
  const body = [
    'Generated by Pickle Rick.',
    '',
    `Session: ${path.basename(sessionDir)}`,
    `Prompt: ${state.original_prompt || '(none)'}`,
  ].join('\n');

  try {
    const output = run_cmd(['gh', 'pr', 'create', '--title', title, '--body', body], {
      cwd: repoPath,
    });
    return output.trim();
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to create PR: ${msg}`);
  }
}

// CLI
if (process.argv[1] && path.basename(process.argv[1]) === 'pr-factory.js') {
  const sessionDir = process.argv[2];
  if (!sessionDir) {
    console.error('Usage: node pr_factory.js <session_dir>');
    process.exit(1);
  }

  try {
    const url = createPR(sessionDir);
    console.log(`${Style.GREEN}PR Created: ${url}${Style.RESET}`);
  } catch (err) {
    console.error(`${Style.RED}Error: ${err instanceof Error ? err.message : String(err)}${Style.RESET}`);
    process.exit(1);
  }
}
